version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: click-battle-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: votreMdpSecurisé
      MYSQL_DATABASE: click_battle_db
      MYSQL_USER: click_battle_user
      MYSQL_PASSWORD: click_battle_pass
    ports:
      - "3307:3306"  # Modifié de 3306:3306 à 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - click-battle-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: click-battle-phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - click-battle-network

networks:
  click-battle-network:
    driver: bridge

volumes:
  db_data: